---

# Apply automatic fixes
APPLY_FIXES: all

# Permissions check makes no sense in CI environment
REPOSITORY_CHECKOV_ARGUMENTS: --skip-check CKV2_GHA_1

#ENABLE_LINTERS:
#  - PYTHON_PYRIGHT
#  - PYTHON_MYPY
#  - PYTHON_BANDIT
#  - PYTHON_FLAKE8
#  - PYTHON_PYLINT

DISABLE_LINTERS:
  - SPELL_CSPELL # cspell doesn't work very well
  - PYTHON_PYLINT

REPOSITORY_SEMGREP_ARGUMENTS: >-
  -c p/comment
  -c p/cwe-top-25
  -c p/default
  -c p/r2c-security-audit
  -c p/python

PRE_COMMANDS:
  - command: pip install -r /github/workspace/requirements.txt
