---

# Apply automatic fixes
APPLY_FIXES: none

# Permissions check makes no sense in CI environment
REPOSITORY_CHECKOV_ARGUMENTS: --skip-check CKV2_GHA_1

ENABLE_LINTERS:
  - PYTHON_PYRIGHT
  - PYTHON_MYPY
  - PYTHON_BANDIT
  - PYTHON_FLAKE8
  - PYTHON_PYLINT

DISABLE_LINTERS:
  - SPELL_CSPELL # cspell doesn't work very well

REPOSITORY_SEMGREP_RULESETS:
  - p/comment
  - p/cwe-top-25
  - p/default
  - p/r2c-security-audit
  - p/python

PRE_COMMANDS:
  - command: pip install -r requirements.txt
    venv: pylint
  - command: pip install -r requirements.txt
    venv: pyright
  - command: pip install -r requirements.txt
    venv: flake8
  - command: pip install -r requirements.txt
    venv: bandit
